name: percy-test
on:
  pull_request:
    branches:
      - main
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          - node-version: 16
        name: install
        run: npm ci
        run: npx percy -v
        run: npx percy snapshot _site
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
