name: percy-test
on: push

jobs:
  VISUAL_TESTING:
    runs-on: ubuntu-latest
    environment: PERCY

    steps:
    - uses: actions/checkout@v1
    - name: Percy
      run: npx percy snapshot ./
      env:
        PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}