name: percy-test
on: push

jobs:
  VISUAL_TESTING:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Percy
      run: npx percy snapshot _site
      env:
        PERCY_TOKEN: ${{PERCY.PERCY_TOKEN}}