name: percy-test
on:
  pull_request:
    branches:
      - main
      - '*'

jobs:
  VISUAL_TESTING:
    runs-on: ubuntu-latest
    environment: PERCY

    steps:
    - uses: actions/checkout@v1
    - name: Percy
      uses: percy/snapshot-action@v0.1.2
      run: npx percy snapshot snapshots.yml
      env:
        PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}