name: percy-test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        name: install
        run: npm ci |
        npx percy -v |
        npx percy snapshot _site |
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
