name: percy-test
on: push

jobs:
  VISUAL_TESTING:
    runs-on: ubuntu-latest
    environment: PERCY

    steps:
    - uses: actions/checkout@v1

    - name: Enviroments
      run: echo "my enviroment is ${{secrets.PERCY_TOKEN}}"

    - name: Percy
      run: npx percy snapshot _site
      env:
        PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}